### ISSUE TITLE
KeyError: 'completions'

### ISSUE THREAD

**Issue by wkrettek** [ckoshka/pyai21#1]
When using pyai21 with personate I'm getting this error with the get function:

Task exception was never retrieved
future: <Task finished name='Task-191' coro=<Asynchronise.schedule_completion() done, defined at /Users/warrenkrettek/Library/Caches/pypoetry/virtualenvs/personate-ofwMyv-q-py3.9/lib/python3.9/site-packages/asynchronise/asynchronise.py:219> exception=KeyError('completions')>
Traceback (most recent call last):
  File "/Users/warrenkrettek/Library/Caches/pypoetry/virtualenvs/personate-ofwMyv-q-py3.9/lib/python3.9/site-packages/asynchronise/asynchronise.py", line 224, in schedule_completion
    async for obj in func(
  File "/Users/warrenkrettek/Desktop/playground/personate/personate/prompts/frame.py", line 345, in get_completion
    completion = await frame.complete()
  File "/Users/warrenkrettek/Desktop/playground/personate/personate/core/frame.py", line 48, in complete
    completion = await self.generator_api(prompt=prompt)
  File "/Users/warrenkrettek/Desktop/playground/personate/personate/core/completions.py", line 8, in default_generator_api
    res = await get(
  File "/Users/warrenkrettek/Library/Caches/pypoetry/virtualenvs/personate-ofwMyv-q-py3.9/lib/python3.9/site-packages/pyai21/completions.py", line 99, in get_ai21
    for compl in json_response['completions']:
KeyError: 'completions'

I've checked that my key valid and it appears to be. I will get valid response about 1/3 of the time and this error the rest of the time.

**Comment by wkrettek** [comment]
Ok, turns out this just comes from having an extra newline in the keyfile, so sometimes it was pulling out a blank line for a key. Just gonna close this.
